overlay: Telephony: Add ims-ext-common to injection path Fixes:
01-18 19:35:49.834  2941  2941 E AndroidRuntime: FATAL EXCEPTION: main
01-18 19:35:49.834  2941  2941 E AndroidRuntime: Process: com.android.phone, PID: 2941
01-18 19:35:49.834  2941  2941 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/codeaurora/ims/QtiImsExtListenerBaseImpl;
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.ScbmHandler.init(ScbmHandler.java:247)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.QtiTelephonyComponentFactory.makeExtTelephonyClasses(QtiTelephonyComponentFactory.java:199)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at com.android.internal.telephony.PhoneFactory.makeDefaultPhone(PhoneFactory.java:297)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at com.android.internal.telephony.PhoneFactory.makeDefaultPhones(PhoneFactory.java:108)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at com.android.phone.PhoneGlobals.onCreate(PhoneGlobals.java:416)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at com.android.phone.PhoneApp.onCreate(PhoneApp.java:39)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1215)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6744)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:248)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2054)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7880)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
01-18 19:35:49.834  2941  2941 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: org.codeaurora.ims.QtiImsExtListenerBaseImpl
01-18 19:35:49.834  2941  2941 E AndroidRuntime: 	... 17 more

Change-Id: I0669f650055054bb27830c7e51f19d665b90ca0d